spring:
  application:
    name: match
  config:
    import: database.yml
  redis:
    host: localhost
    port: 6379
  mail:
    host: smtp.gmail.com        # SMTP 서버 호스트
    port: 587                   # SMTP 서버 포트
    username: sudden3415@gmail.com                   # SMTP 서버 로그인 아이디
    password: hqxfwujbrxwjuwzo                   # SMTP 서버 로그인 비밀번호
    properties:
      mail:
        smtp:
          auth: true            # 사용자 인증 시도 여부
          starttls:
            enable: true        # starttls 활성화 여부

server:
  port: 8099
  servlet:
    session:
      timeout: 30m